"""add security question fields to users

Revision ID: 06b9c3109412
Revises: 1bfc3359e798
Create Date: 2026-06-26 23:37:41.659685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b9c3109412'
down_revision = '1bfc3359e798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('security_answer_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('security_answer_hash')
        batch_op.drop_column('security_question')

    # ### end Alembic commands ###
