"""add prepayment model registry indexes

Revision ID: 9b2655c8fd02
Revises: b92b82b49f76
Create Date: 2026-07-16 10:26:44.318739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2655c8fd02'
down_revision = 'b92b82b49f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prepayment_model_registry', schema=None) as batch_op:
        batch_op.create_index('ix_prepayment_model_registry_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index('ix_prepayment_model_registry_user_temp', ['user_id', 'is_temporary'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prepayment_model_registry', schema=None) as batch_op:
        batch_op.drop_index('ix_prepayment_model_registry_user_temp')
        batch_op.drop_index('ix_prepayment_model_registry_user_active')

    # ### end Alembic commands ###
