"""add is_temporary to prepayment model registry

Revision ID: b92b82b49f76
Revises: f56e276b68c2
Create Date: 2026-07-15 17:33:44.963423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92b82b49f76'
down_revision = 'f56e276b68c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prepayment_model_registry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_temporary', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prepayment_model_registry', schema=None) as batch_op:
        batch_op.drop_column('is_temporary')

    # ### end Alembic commands ###
