"""Add pdf_data column to reports table

Revision ID: c1a2f3b4d5e6
Revises: 9b2655c8fd02
Create Date: 2026-07-23 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c1a2f3b4d5e6"
down_revision = "9b2655c8fd02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pdf_data", sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_column("pdf_data")
    # ### end Alembic commands ###
