"""add prepayment model registry table

Revision ID: f56e276b68c2
Revises: 06b9c3109412
Create Date: 2026-07-15 14:41:00.126823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56e276b68c2'
down_revision = '06b9c3109412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prepayment_model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=True),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('target_variable', sa.String(length=255), nullable=False),
    sa.Column('feature_columns_json', sa.JSON(), nullable=True),
    sa.Column('hyperparameters_json', sa.JSON(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('preprocessing_json', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('artifact_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_backend', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prepayment_model_registry')
    # ### end Alembic commands ###
